### ISSUE TITLE
Fix enologs.tool

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/enochecker3#13]
It always says enochecker3 instead of e.g. StldoctorChecker

**Comment by Sinitax** [comment]
Its redundant to make enologs.tool the checker name (as it is in enochecker(1)), there is no sense in naming a checker anything other than <SERVICE>Checker. This is already the status-quo since enochecker(1) creates the logged "service_name" by splitting the checker class name by "Checker" (https://github.com/enowars/enochecker/blob/main/src/enochecker/enochecker.py#L189).

I suggest we either leave enologs.tool as the checker library (and enforce this in enochecker(1)) or remove it altogether.

You should be able to filter by enologs.service_name instead of enologs.tool either way.

**Comment by Trolldemorted** [comment]
>You should be able to filter by enologs.service_name instead of enologs.tool either way.

Other components (such as the engine, launcher and flag submission) are also logging data with `serviceName` set, and we do not prevent services from having central (e.g. coordinating, forwarding or aggregating) ancillary components, which are operated by us and should log with `serviceName` set as well.

For checkers, adding the `Checker` suffix is the best we can do, which #25 should solve nicely

**Comment by Sinitax** [comment]
Ok, I see the issue now. Fixed enologs.tool in #25.
